#!/usr/bin/env bash
# installing nginx and redirecting
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i 's/server_name _;/&\n	location \/redirect_me {\n	    return 301 https:\/\/www.youtube.com\/watch?v=dBmxNsS3BGE;\n	}/' /etc/nginx/sites-available/default
service nginx start
