#!/usr/bin/env bash
# installing nginx and redirecting and errors
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i 's/server_name _;/&\n    error_page 404 =200 \/404.html;/' /etc/nginx/sites-available/default
service nginx start
