#!/usr/bin/env bash
#firewall redirects port 8080/TCP to port 80/TCP
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to :80sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to :80
