#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new

systemctl restart networking
